### ISSUE TITLE
Feature Request: close button for destroy suggestion list container

### ISSUE THREAD

**Issue by xeronce** [dab246/super_tag_editor#1]
I think there is no **close button for destroy suggestion list container**. Have any option to close manually?

**Comment by dab246** [comment]
> I think there is no **close button for destroy suggestion list container**. Have any option to close manually?

@xeronce Thanks for your comment. I will update as soon as possible.

**Comment by dab246** [comment]
@xeronce 
- You can activate/deactivated the suggestion box by changing the value of the variable `activateSuggestionBox`.
- Please update to the latest version `0.0.2` at [pub.dev](https://pub.dev/packages/super_tag_editor) to use this feature.
