### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by YouSour** [dab246/super_tag_editor#11]
hi, i just test with this package i don't see anything related with validation , i think it is important with development. any plan ?

**Comment by dab246** [comment]
> hi, i just test with this package i don't see anything related with validation , i think it is important with development. any plan ?

Thanks @YouSour 
I have implemented the `validation` feature in the latest code on my `github`. But I haven't had time to `publish` it to `pub.dev` yet. You can `fetch master` on my github to use it or wait for me to update again on `pub.dev`. Thanks.

**Comment by YouSour** [comment]
@dab246 thank you for reply, i want to try it, do you have any example that implement with validation ?

**Comment by dab246** [comment]
> @dab246 thank you for reply, i want to try it, do you have any example that implement with validation ?

@YouSour  Please see this PR #7

**Comment by YouSour** [comment]
@dab246  thanks
