### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by maverick42** [dab246/super_tag_editor#18]
Hi,

When entering a new tag, there is no search to check if the entry is duplicated. The suggestion does not take into account tags already entered. 

Regards
Fréderik

**Comment by dab246** [comment]
> Hi,
> 
> When entering a new tag, there is no search to check if the entry is duplicated. The suggestion does not take into account tags already entered.
> 
> Regards Fréderik

Thanks, IMO, You can save the tags entered into the list in memory and pass it to the `findSuggestions` property

**Comment by dab246** [comment]
> Hi,
> 
> I followed your idea. In my code :
> 
> * AllTagsList contains the list of all tags
> * _selectedTags contains the list of tags entered
> 
> ```
> findSuggestions: (String query) {
>                   if (query.isNotEmpty) {
>                     var lowercaseQuery = query.toLowerCase();
>                     var filteredList = allTagsList
>                         .where((tag) =>
>                             !_selectedTags.contains(tag) &&
>                             (tag.toLowerCase().startsWith(lowercaseQuery) ||
>                                 tag.toLowerCase().contains(lowercaseQuery)))
>                         .toList(growable: false);
> 
>                     filteredList.sort((a, b) => a
>                         .toLowerCase()
>                         .indexOf(lowercaseQuery)
>                         .compareTo(b.toLowerCase().indexOf(lowercaseQuery)));
> 
>                     return filteredList;
>                   }
>                   return [];
>                 },
> ```

@maverick42  You can use `toSet()` of collection to remove duplicate elements. Ex: `return filteredList.toSet().toList();`
