### ISSUE TITLE
Treat the 'return' key as confirmation of a new tag entry

### ISSUE THREAD

**Issue by davoutuk** [dab246/super_tag_editor#28]
Is it possible to `adapt your super_tag_editor widget so that the 'return' key is taken as a user input to accept the just typed text as a new tag entry?

For example,  I type the characters 'A', then 'B' and then 'C'.  At this point if I select the 'return' key then the 'ABC' entry would be accepted as a new tag

**Comment by dab246** [comment]
> Is it possible to `adapt your super_tag_editor widget so that the 'return' key is taken as a user input to accept the just typed text as a new tag entry?
> 
> For example, I type the characters 'A', then 'B' and then 'C'. At this point if I select the 'return' key then the 'ABC' entry would be accepted as a new tag

Hi @davoutuk We now support it in our project. You can import and use it. Additionally you can add characters to confirm the generation of `tag` when pressed by adding it to the `delimiters` attribute.

**Comment by davoutuk** [comment]
Is  this change published to pub.dev?

**Comment by dab246** [comment]
> Is this change published to pub.dev?

It is already supported on version `0.2.0` on pub.dev
